import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thiluxan | Full Stack Developer</title>
        <link rel="icon" href="/assets/navLogo.png" sizes="16x16" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
